Better errors and memory management
EllenNyan/ArcheTape pull request #10
Opened 2020-12-30 07:07 UTC by asquared31415

Changes some `.unwrap()` into `.expect(reason)` to clarify the source of the error
Adds additional error handling in some locations
Properly handles allocation errors with `handle_alloc_error`
Does not allocate in EntityBuilder when not needed

2020-12-30 08:28 UTC, EllenNyan requested changes

2020-12-30 08:28 UTC, BoxyUwU commented on src/entities.rs
> +        let generation = entity.generation();
Can you move this to above the match block since its not used until then

2020-12-30 08:28 UTC, BoxyUwU commented on src/entity_builder.rs
> +            data: NonNull::new(data).unwrap_or_else(|| handle_alloc_error(layout)),
Can you move this to a local

2020-12-30 08:28 UTC, BoxyUwU commented on src/entity_builder.rs
> +            self.data = NonNull::new(new_ptr).unwrap_or_else(|| handle_alloc_error(layout));
This is using a ``layout`` with the size set to the old capacity not a layout with the size of new_size

2020-12-30 08:28 UTC, EllenNyan commented on src/entity_builder.rs
> +            self.cap = new_size;
We should move this to after we set self.data to the new pointer

2020-12-31 20:17 UTC, EllenNyan approved these changes

2021-01-01 18:47 UTC, asquared31415 commented
I think this is ready now

2021-01-02 12:58 UTC, merged

2021-01-02 13:12 UTC, EllenNyan commented
:) thank u